CREATE TABLE CLIENT
(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	AGE INT NOT NULL,
	LAST_UPDATE DATE NOT NULL
)

CREATE TABLE CREDIT_CARD
(
	CARD_NUMBER int PRIMARY KEY NOT NULL,
	CVV INT NOT NULL,
	ID_CLIENT INT NOT NULL,
	EXPIRATION VARCHAR(25) NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE SALE
(
	ID SERIAL PRIMARY KEY,
	ID_CLIENT INT NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	TOTAL DECIMAL  NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_SALE FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE PHONE_CLIENT
(
	ID SERIAL PRIMARY KEY,
	ID_CLIENT INT NOT NULL,
	NUMBER INT NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_PHONE FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE ADDRESS_CLIENT
(
	ID SERIAL PRIMARY KEY,
	ID_CLIENT INT NOT NULL,
	ADDRESS INT NOT NULL,
	ADDRESS_NAME VARCHAR(50) NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_ADDRESS FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE EMAIL_CLIENT
(
	ID SERIAL PRIMARY KEY,
	ID_CLIENT INT NOT NULL,
	EMAIL INT NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_EMAIL FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)






