CREATE TABLE CLIENT
(
	ID INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	LAST_NAME VARCHAR(50) NOT NULL,
	AGE INT NOT NULL,
	LAST_UPDATE DATE NOT NULL
)

CREATE TABLE CREDIT_CARD
(
	CARD_NUMBER varchar(255) NOT NULL,
	CVV varchar(3) NOT NULL,
	ID_CLIENT INT NOT NULL,
	EXPIRATION VARCHAR(25) NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE SALE
(
	ID_CLIENT INT NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	TOTAL DECIMAL  NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_SALE FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE PHONE_CLIENT
(
	ID_CLIENT INT NOT NULL,
	NUMBER varchar(50) NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_PHONE FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE ADDRESS_CLIENT
(
	ID_CLIENT INT NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	ADDRESS_NAME VARCHAR(50) NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_ADDRESS FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

CREATE TABLE EMAIL_CLIENT
(
	ID_CLIENT INT NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	LAST_UPDATE DATE NOT NULL,
	CONSTRAINT FK_ID_CLIENT_EMAIL FOREIGN KEY(ID_CLIENT) REFERENCES  CLIENT(ID)
)

